### ISSUE TITLE
Move to BitBucket?

### ISSUE THREAD

**Issue by jfalkner** [evolvedmicrobe/smrtlink-conditions-app#1]
@evolvedmicrobe Why in GitHub? Seems like this one should be moved to BitBucket along with the rest of new stuff.

**Comment by evolvedmicrobe** [comment]
Bitbucket is the main repo, http://bitbucket.nanofluidics.com:7990/projects/ITG/repos/smrtlink-conditions-app/browse, but I am mirroring it here so I can browse it from the web when VPN is down.
